name: Angular Practice CI
on: 
  push:
    branches:
      - master
permissions:
  contents: write # Required to deploy to GitHub Pages
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build:prod

      - name: Deploy to gh pages
        run: |
          npx angular-cli-ghpages --dir=dist/angular-practice-v2/browser --no-silent
        env:
          CI: true
          GH_TOKEN: ${{ secrets.GH_TOKEN }}